# Jekyll configuration

name: zenBlog
description: I write in here sometimes about some stuff :) tech related but sometimes not idk

# Url is currently only used only for the RSS feed in feed.xml
url: http://zenandroid.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: zenAndroid
copyright: 2015-2020

social:
  github: zenAndroid
  rss: feed.xml

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
# paginate: 5

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
